apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-kubernetes-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JuanMaFraile/ProyectoKubernetes.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: santiadi/grupojava
        - name: image.tag
          value: stable
        - name: replicaCount
          value: "5"
        - name: service.type
          value: LoadBalancer
        - name: ingress.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 